const mongoose = require('mongoose');
const { Schema } = mongoose;

/**
 * Ticket Model
 *
 * ticket_code     : human-readable unique ID  e.g. TKT-00042
 * company_subdomain embedded for fast look-up by code without a company join
 * peoples         : every stakeholder in the ticket (customer, extra customers added by agents, assigned agent)
 *                   Owner / admin are NOT listed here — they can see every ticket in their company
 * messages        : conversation thread (sender ref + body + optional attachments)
 */

// ─── Sub-schemas ──────────────────────────────────────────────────────────────

const attachmentSchema = new Schema(
  {
    url: { type: String, required: true },
    filename: { type: String, required: true },
    mimetype: { type: String },
    size: { type: Number }, // bytes
  },
  { _id: false }
);

const messageSchema = new Schema(
  {
    sender: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // For guest / track-session senders we store their email as a fallback
    senderEmail: { type: String },
    /** Display name for AI / visitor bubbles (kept out of body text) */
    senderName: { type: String, trim: true },
    body: {
      type: String,
      required: [true, 'Message body is required'],
      maxlength: [50000, 'Message cannot exceed 50 000 characters'],
    },
    attachments: { type: [attachmentSchema], default: [] },
    sentAt: { type: Date, default: Date.now },
    // Internal notes (only visible to agents / admins / owner)
    isInternal: { type: Boolean, default: false },
    /** True when the message was generated by Agentra AI Agent */
    isAi: { type: Boolean, default: false },
    /** Centered timeline notice (handoff, agent joined, etc.) — not a customer/agent bubble */
    isSystem: { type: Boolean, default: false },
    contentType: {
      type: String,
      enum: ['text', 'system_event'],
      default: 'text',
    },
    eventType: { type: String, trim: true },
  },
  { _id: true }
);

const peopleSchema = new Schema(
  {
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // 'customer' | 'agent' | 'cc'
    role: {
      type: String,
      enum: ['customer', 'agent', 'cc'],
      required: true,
    },
    addedAt: { type: Date, default: Date.now },
    addedBy: { type: Schema.Types.ObjectId, ref: 'User' }, // null = self (creator)
  },
  { _id: false }
);

// ─── Main schema ──────────────────────────────────────────────────────────────

const ticketSchema = new Schema(
  {
    // ── Identification ────────────────────────────────────────────────────────
    ticket_code: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
    },

    // Denormalized for quick public tracking (no company join needed)
    company_subdomain: {
      type: String,
      required: true,
      lowercase: true,
      trim: true,
    },

    company: {
      type: Schema.Types.ObjectId,
      ref: 'Company',
      required: true,
    },

    // ── Content ───────────────────────────────────────────────────────────────
    ticket_title: {
      type: String,
      required: [true, 'Ticket title is required'],
      trim: true,
      maxlength: [200, 'Title cannot exceed 200 characters'],
    },

    ticket_description: {
      type: String,
      required: [true, 'Ticket description is required'],
      maxlength: [50000, 'Description cannot exceed 50 000 characters'],
    },

    // ── Classification ────────────────────────────────────────────────────────
    department: {
      type: Schema.Types.ObjectId,
      ref: 'Department',
    },

    // Multiple teams can be assigned
    teams: [{ type: Schema.Types.ObjectId, ref: 'Team' }],

    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'urgent'],
      default: 'medium',
    },

    status: {
      type: String,
      enum: [
        'open',
        'in_progress',
        'on_hold',
        'resolved',
        'closed',       // closed by agent/admin/owner
        'self_closed',  // closed by customer themselves
      ],
      default: 'open',
    },

    inboxFolder: {
      type: String,
      enum: ['inbox', 'snoozed', 'trash', 'spam'],
      default: 'inbox',
    },

    snoozedUntil: { type: Date },

    // ── Channel & classification metadata ─────────────────────────────────────
    source: {
      type: String,
      enum: ['portal', 'email', 'chat', 'chatbot', 'instagram', 'facebook', 'whatsapp', 'tiktok'],
      default: 'portal',
    },

    tags: [{ type: String, trim: true }],

    isUnread: { type: Boolean, default: false },

    // Merge / incident ops (Helpdesk AI phase 3)
    mergedInto: { type: Schema.Types.ObjectId, ref: 'Ticket' },
    mergedIntoCode: { type: String },
    mergedFromCodes: [{ type: String }],
    incidentKey: { type: String },

    // ── Facebook Messenger linkage (source === 'facebook') ────────────────────
    // Lets inbound webhooks find the right conversation and lets agent replies
    // route back to the correct Messenger recipient.
    facebook: {
      pageId: { type: String },
      psid: { type: String }, // Page-scoped ID of the Messenger user
    },

    // ── Instagram DM linkage (source === 'instagram') ─────────────────────────
    instagram: {
      igUserId: { type: String }, // our Instagram business account id
      igsid: { type: String }, // Instagram-scoped ID of the customer
    },

    // ── WhatsApp linkage (source === 'whatsapp') ──────────────────────────────
    whatsapp: {
      phoneNumberId: { type: String }, // our Cloud API phone number id
      waId: { type: String }, // customer's WhatsApp id (phone number)
    },

    // ── Email linkage (source === 'email') ────────────────────────────────────
    email: {
      fromAddress: { type: String }, // customer's email address
      lastMessageId: { type: String }, // Message-ID of the latest email in thread
      references: { type: String }, // accumulated References header for threading
    },

    details: {
      contactReason: { type: String, default: '' },
      product: { type: String, default: '' },
      resolution: { type: String, default: '' },
      customerType: { type: String, default: '' },
      customerNote: { type: String, default: '' },
      customerPhone: { type: String, default: '' },
      customerEmail: { type: String, default: '' },
    },

    // Helpdesk AI overview / copilot output (regenerated on handoff or demand)
    aiIntelligence: {
      summary: { type: String, default: '' },
      customerWant: { type: String, default: '' },
      sentiment: {
        type: String,
        enum: ['positive', 'neutral', 'frustrated', 'angry', 'unknown'],
        default: 'unknown',
      },
      urgency: {
        type: String,
        enum: ['low', 'medium', 'high', 'critical', 'unknown'],
        default: 'unknown',
      },
      intent: { type: String, default: '' },
      language: { type: String, default: '' },
      handoffReason: { type: String, default: '' },
      actionsAlreadyTried: [{ type: String }],
      recommendedAction: {
        type: {
          type: String,
          default: 'none',
        },
        label: { type: String, default: '' },
        reason: { type: String, default: '' },
        confidence: { type: Number, default: 0, min: 0, max: 100 },
      },
      risks: [
        {
          type: { type: String },
          severity: {
            type: String,
            enum: ['low', 'medium', 'high', 'critical'],
            default: 'medium',
          },
          message: { type: String },
        },
      ],
      suggestedReply: { type: String, default: '' },
      suggestedTags: [{ type: String }],
      suggestedPriority: {
        type: String,
        enum: ['low', 'medium', 'high', 'urgent', ''],
        default: '',
      },
      sources: [{ type: String }],
      contradictions: [
        {
          type: { type: String },
          severity: {
            type: String,
            enum: ['low', 'medium', 'high', 'critical'],
            default: 'medium',
          },
          message: { type: String },
        },
      ],
      similarTickets: [
        {
          ticketCode: { type: String },
          title: { type: String },
          status: { type: String },
          similarity: { type: Number },
          outcome: { type: String },
          responseThatWorked: { type: String },
          resolvedBy: { type: String },
          closedAt: { type: Date },
        },
      ],
      waitingOn: {
        type: String,
        enum: [
          '',
          'customer',
          'warehouse',
          'courier',
          'manager',
          'payment_provider',
          'agent',
          'none',
        ],
        default: '',
      },
      generatedAt: { type: Date },
      model: { type: String },
    },

    // Manager AI quality score (scored after resolve/close)
    aiQa: {
      accuracy: { type: Number },
      empathy: { type: Number },
      tone: { type: Number },
      policyCompliance: { type: Number },
      resolutionQuality: { type: Number },
      overall: { type: Number },
      flags: [{ type: String }],
      summary: { type: String },
      needsManagerReview: { type: Boolean, default: false },
      coachingTip: { type: String },
      scoredAt: { type: Date },
      model: { type: String },
    },

    // Customer rating captured when a live-chat conversation is resolved.
    // resolvedAgent remains stable even if the ticket is reassigned later.
    customerSatisfaction: {
      rating: { type: Number, min: 1, max: 5 },
      label: { type: String },
      agent: { type: Schema.Types.ObjectId, ref: 'User' },
      session: { type: Schema.Types.ObjectId, ref: 'ChatSession' },
      requestedAt: { type: Date },
      submittedAt: { type: Date },
    },

    // ── Attachments (top-level; messages can also have attachments) ───────────
    attachments: { type: [attachmentSchema], default: [] },

    // ── Stakeholders ──────────────────────────────────────────────────────────
    // Does NOT include owner / admin — they see all tickets in their company
    peoples: { type: [peopleSchema], default: [] },

    // Convenience shortcut — the primary assigned agent (also reflected in peoples)
    assigned_agent: {
      type: Schema.Types.ObjectId,
      ref: 'User',
    },

    // ── Conversation ──────────────────────────────────────────────────────────
    messages: { type: [messageSchema], default: [] },

    // ── Activity ──────────────────────────────────────────────────────────────
    lastActivity: { type: Date, default: Date.now },
    closedAt: { type: Date },
    closedBy: { type: Schema.Types.ObjectId, ref: 'User' },

    // ── Created by ───────────────────────────────────────────────────────────
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
ticketSchema.index({ company: 1, status: 1 });
ticketSchema.index({ company: 1, createdAt: -1 });
// ticket_code already declares `unique: true` on the field itself.
ticketSchema.index({ company_subdomain: 1, ticket_code: 1 });
ticketSchema.index({ 'peoples.user': 1 });
ticketSchema.index({ assigned_agent: 1 });
ticketSchema.index({ company: 1, inboxFolder: 1, status: 1 });
ticketSchema.index({ company: 1, source: 1, 'facebook.psid': 1 });
ticketSchema.index({ company: 1, source: 1, 'instagram.igsid': 1 });
ticketSchema.index({ company: 1, source: 1, 'whatsapp.waId': 1 });
ticketSchema.index({ company: 1, source: 1, 'email.fromAddress': 1 });

// ─── Static: generate the next ticket code for a company ─────────────────────

const CODE_COUNTER_KEY = 'ticketCodeSeq';

/**
 * Highest numeric suffix already used by this company, so existing workspaces
 * continue their sequence instead of restarting at 1.
 */
async function highestUsedSequence(TicketModel, companyId) {
  const [row] = await TicketModel.aggregate([
    { $match: { company: new mongoose.Types.ObjectId(String(companyId)) } },
    {
      $project: {
        seq: {
          $convert: {
            input: { $arrayElemAt: [{ $split: ['$ticket_code', '-'] }, -1] },
            to: 'int',
            onError: 0,
            onNull: 0,
          },
        },
      },
    },
    { $group: { _id: null, max: { $max: '$seq' } } },
  ]);
  return row?.max || 0;
}

/**
 * Next ticket code for a company.
 *
 * Backed by an atomic per-company counter rather than a document count: counting
 * reuses sequences after a ticket is deleted, which permanently collides with the
 * unique ticket_code index. `ticket_code` is unique across the whole collection,
 * so codes already claimed by another workspace are skipped too.
 */
ticketSchema.statics.generateCode = async function (companyId, prefix = 'TKT') {
  const Counter = require('./Counter');
  const scope = `company:${companyId}`;
  const cleanPrefix = String(prefix || 'TKT').toUpperCase();

  // Seed once from existing tickets. $max keeps concurrent seeding idempotent.
  const current = await Counter.get(scope, CODE_COUNTER_KEY);
  if (!current) {
    const seeded = await highestUsedSequence(this, companyId);
    if (seeded > 0) {
      await Counter.updateOne(
        { scope, key: CODE_COUNTER_KEY },
        { $max: { value: seeded } },
        { upsert: true },
      );
    }
  }

  for (let attempt = 0; attempt < 100; attempt += 1) {
    const seq = await Counter.increment(scope, CODE_COUNTER_KEY);
    const code = `${cleanPrefix}-${String(seq).padStart(5, '0')}`;
    const taken = await this.exists({ ticket_code: code });
    if (!taken) return code;
  }

  // Sequence space is unexpectedly crowded — fall back to a collision-proof code.
  return `${cleanPrefix}-${Date.now().toString(36).toUpperCase()}`;
};

/**
 * Create a ticket with a freshly generated code, retrying if another writer
 * claims the same code in the gap between generating and inserting.
 */
ticketSchema.statics.createWithCode = async function (companyId, prefix, doc) {
  let lastErr;
  for (let attempt = 0; attempt < 5; attempt += 1) {
    const ticket_code = await this.generateCode(companyId, prefix);
    try {
      return await this.create({ ...doc, ticket_code });
    } catch (err) {
      const duplicateCode = err?.code === 11000 && 'ticket_code' in (err.keyPattern || err.keyValue || {});
      if (!duplicateCode) throw err;
      lastErr = err;
    }
  }
  throw lastErr;
};

module.exports = mongoose.model('Ticket', ticketSchema);
